DOCKER_IMAGE := ps3-fps-unlocker-dev

.PHONY: docker-image docker-build docker-pkg clean help

help:
	@echo "PS3 FPS Unlocker Docker Build"
	@echo ""
	@echo "Targets:"
	@echo "  docker-image  Build PS3DEV/PSL1GHT image"
	@echo "  docker-build  Build SELF"
	@echo "  docker-pkg    Build installable PKG"
	@echo "  clean         Remove build artifacts"

docker-image:
	@docker build -t $(DOCKER_IMAGE) .

docker-build: docker-image
	@docker run --rm --platform linux/amd64 -v "$(CURDIR)":/src -w /src $(DOCKER_IMAGE) make

docker-pkg: docker-image
	@docker run --rm --platform linux/amd64 -v "$(CURDIR)":/src -w /src $(DOCKER_IMAGE) make pkg

clean:
	@rm -rf build *.elf *.self *.fake.self *.pkg *.gnpdrm.pkg

